name: skedule
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0' # It's good practice to use a range

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  supabase_flutter: ^2.5.2
  http: ^1.2.1

  # UI & Utility Packages
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  draggable_fab: ^0.1.4 # <-- 1. THIS IS THE CORRECT PACKAGE NAME
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0 # Added this for your splash screen

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # 2. CORRECT INDENTATION FOR ASSETS
  assets:
    - assets/google_logo.png
    - assets/app_logo.jpg # It's better to declare the directory
    - .env

# 3. THIS BLOCK MUST BE OUTSIDE AND AT THE SAME LEVEL AS `flutter:`
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.jpg" # <-- 4. STRONGLY RECOMMEND USING A .PNG
  min_sdk_android: 21

# Also add the splash screen config here
flutter_native_splash:
  color: "#F4F6FD"
  image: assets/app_logo.jpg